backend:
  name: proxy
  proxy_url: https://hadron.tail859af.ts.net/api/v1
  base_url: https://hadron.tail859af.ts.net

local_backend: true

media_folder: "assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Header"
        name: "header"
        widget: "object"
        fields:
          - { label: "Teaser Image", name: "teaser", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
